# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180928_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Image')),
            ],
        ),
    ]
