# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180929_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location_name',
        ),
    ]
