# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
