# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_location_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, null=True)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Image')),
            ],
        ),
    ]
