# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_image_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/'),
            preserve_default=False,
        ),
    ]
